### ISSUE TITLE
python-bluez fails to install

### ISSUE THREAD

**Issue by 555learnwithme555** [BLeeEZ/rpi-kvm#1]
Thank you for your project. I am facing issue while installing rpi-kvm. Could you look into this and help me in installing.

Please find below image for reference:
![raspberrypi](https://user-images.githubusercontent.com/25825035/161084254-c56c0b73-9f04-45db-b5db-bcabffbca98a.PNG)

**Comment by 555learnwithme555** [comment]
@BLeeEZ  I have observed that the raspberry pi is able to show as Bluetooth device but  it fails to  show it from webpage and fails to search nearby device. When trying to connect the shown Bluetooth device from other devices like laptop it asks for security pin to connect. I have tried reinstalling raspberry pi OS from previous version but that also seems to not work. Still trying to figuring out how to fix it.

**Comment by BLeeEZ** [comment]
Currently the webpage only displays already connected and paired Bluetooth partners. I haven’t yet encountered a security pin request. I install as described in the readme. Then go the Mac/Pc/Mobile phone and search for clients. Establish a connection to rpi-kvm. Then the device is visible in the bt clients webpage.

**Comment by 555learnwithme555** [comment]
Thanks for letting me know. Gonna do it again and check,

**Comment by 555learnwithme555** [comment]
@BLeeEZ I have followed the instructions provided in the readme and installed it on the raspberry pi. Now what happens is the installation gets completed successfully and their is an error when restarting the Bluetooth service loading with the new configuration. Apart from that in raspberry pi it is unable to search for devices around it and it broadcast raspberry pi Bluetooth name. I am able to view broadcast name form devices like laptop and phone, but when I tried to connect it asks for entering pin. Tried installing in different directories(not sure whether I did it right, just gave a shot). Thanks a lot for your time and effort looking in to this.

I have also attached recent screenshots for your reference:

![raspberrypi](https://user-images.githubusercontent.com/25825035/161838044-8d4e255b-4651-476b-885a-f43ea7c25b2f.PNG)

![raspberrypi 1](https://user-images.githubusercontent.com/25825035/161838059-be97adf2-40a4-4b32-8f48-1c474e805975.PNG)

![raspberrypi 2](https://user-images.githubusercontent.com/25825035/161838083-0eefd7b3-9580-453c-a538-f6889da87a15.PNG)

![raspberrypi3](https://user-images.githubusercontent.com/25825035/161838119-1a79b9d2-7c95-4647-9f20-1c08bbaef7ac.PNG)

**Comment by BLeeEZ** [comment]
Mhh, my implementation uses bluez via dbus.
You can use `bluetoothctl` like described here: https://www.makeuseof.com/manage-bluetooth-linux-with-bluetoothctl/
Via `bluetoothctl` you can add your devices manually, even with pin. When the devices are added, they should appear in rpi-kvm. I hope that helps.

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , hoping you are having fine day. It is really a learning journey for me trying to make this project work for me. Thanks a lot for suggestions in fixing in this. Recent findings while to make it work are the following.

1.) Recent Raspios has changed the location of bluetoothd and I tried manually coping the directory to the specified location based on the installation script, which partially enabled Bluetooth and it did not work.

2.) Downgraded the Rasoios version to 2021-03-04-raspios and upon checking the location of bluetoothd it is seems to be in right location and it was able to scan bluettoth and connect. But it seems it is not broadcasting as HID device.

(I had to run this command in order to install dependencies files apt-get update --allow-releaseinfo-change )

3.)Being confused I opened inspect in chrome, I was able to see below errors.

![Screenshot 2022-04-14 055839 PNG](https://user-images.githubusercontent.com/25825035/163324441-eb3ba4c9-6039-4b35-af61-d6a2a796d437.jpg)

![Screenshot 2022-04-14 055933](https://user-images.githubusercontent.com/25825035/163324447-dd3c5bcf-5824-4081-94cd-215b95d51ede.jpg)

![Screenshot 2022-04-14 055957](https://user-images.githubusercontent.com/25825035/163324450-1e154f66-5dbe-4dc3-8840-ff38781be10e.jpg)

Can you please check and let me know what to do next to fix? It would be really helpful for me and others who want to try your wonderful utility project.

**Comment by BLeeEZ** [comment]
Hi,
1) My raspberry pi is still running on raspian "buster".
2) See 1)
3) Oh my god... I hard coded and committed my raspberry pi device name. This is the reason why you get the error message. I need to fix this. For an easy fast fix for you: search for "zimba-kvm" and replace all occurrences with the device name of your raspberry pi.

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , hoping you are having fine day. Tried your suggested fix by renaming raspberry pi to zimba kvm to test and it reduced lots of errors but still having trouble making it work. 

These are my new findings:

1. Bluetooth device connects but as a music device for recent raspberry pi os.
2. Tried buster and it is showing up a hid device I guess but it is throwing D bus errors.
3. Trying the very best to troubleshoot and I hope we will be able to fix it soon. (Looking forward)

Thanks a lot for all your efforts. I am learning new things on the process making it work.

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , thanks for the recent changes you have made. It had improved a lot and brought some hope to me. I am still facing some issue and these are my recent discovery.

1.) I am using2019-07-10-raspbian-buster for less trouble and to be on same page.
2.) Now I am able to connect to Bluetooth with out an issue.
3.) There is now error in  the first screenshot something about dbus.
4.) In the web there is only one error.
5.) The list of connected Bluetooth devices in Bt-Clients is still not showing up.

I have still tried today installing in other OS as well and no luck in making it work. Can you please look and suggest what should be done next to fix the above issues and make it work.

![04](https://user-images.githubusercontent.com/25825035/167022401-3503f19d-a5c4-4374-b1bb-01521d2e52c4.jpg)
![01](https://user-images.githubusercontent.com/25825035/167022412-eac0004d-213c-44c4-b433-38607c951f7d.jpg)
![02](https://user-images.githubusercontent.com/25825035/167022416-c7ed85ae-2562-4410-ab77-2bd5dd1bf279.jpg)
![03](https://user-images.githubusercontent.com/25825035/167022418-69df88a8-eb5d-475e-a26a-60de42ec2d9a.jpg)

**Comment by BLeeEZ** [comment]
1) ok that should simplify the process
2) nice this is one big step
3) i will take a look at this issue. I am in vacation so it will take some time till I can respond.
4) you can ignore this error. I have no custom favicon for this project, so it can't be loaded.
5) i think this issue is connected to 3)

**Comment by BLeeEZ** [comment]
I fixed a missing 'None' check in the bluetooth server which lead to an exception. It is fixed in this commit 60d15d49ec40f476854d006b1e48975827f11167.
Can you update and check again?

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , I am jumping with joy as it has finally worked. Thanks a lot for your active effort and support for your project you have build.

Things I have observed and what I am planning to do next are below.

1.) I have installed Raspberry pi with desktop. So what ever I do on other devices it acts the same in the raspberry pi  is there anything I can do about it.
2.) I am also planning to try this on other version of raspberry OS version So I could help anyone facing similar issue.
3.) I am noob to Linux, so I have doubt whether we could make it as standalone install kind of thing as each time something changes in Linux version it is breaking something. More like predownloaded files and all we have to do is install without depending on the internet.
4.) One more question are you running your raspberry pi without desktop?

**Comment by BLeeEZ** [comment]
Hi, I am very happy that it finally works on your system.
I am running my system headless. My pi is sitting under my desk. Only the connected LCD display is sitting on my desk to show me the time and active clients. I am connecting to it via `Visual Studio Code` with the `Remote Development` Extension (it works over ssh).

2.) Sounds cool but I am currently lacking time to do these updates. This is true for 3.) too.
5.) What do you mean with drag and drop? 
6.) Oh well I think you are right. I haven't noticed it yet because I haven't used my pi with a monitor yet. I think this should definitely be improved.

I am really happy and open to hear that you want to help to improve this project. Your proposed features are all sounding great.

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , I can totally understand, as free time and relaxed mind plays major supporting agent to build anything and even I am struggling with it. I have made the raspberry pi headless now by uninstalling desktop GUI and may be I found the minor lag due to my Bluetooth mouse. I am so excited to test many new things I got in mind and share it with everyone, which requires more of trial and error as I am learning how to use Linux and programming. Is there any best way to reach out to you other than GitHub. Happy Vacation!

**Comment by BLeeEZ** [comment]
You can find my contact information here: https://www.familie-zimba.de/contact

**Comment by 555learnwithme555** [comment]
Thanks @BLeeEZ , I’ll be in touch with you.

**Comment by dsendri** [comment]
Hello,

I have been testing the software using the latest update from you. 
I could confirm that it is working using the latest update.
I am running raspberry pi 400 using the latest bullseye. On the latest os, I had to modify bluetooth.service:
From this: ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=input
To this: **_ExecStart=/usr/libexec/bluetooth/bluetoothd --noplugin=input_**

Hope this help.

Thanks very much.

**Comment by BLeeEZ** [comment]
Nice to hear and thank you for the ExecStart notice. I am currently thinking about a fix for the difference in Bluetooth service path.
My current first idea is to check (in the install script) where the Bluetooth service is located and then adjust the path via regex. Does someone of you has a better solution to this problem?

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , that would be prefect.

**Comment by 555learnwithme555** [comment]
@BLeeEZ , I am not sure, whether we could implement a prompt for conforming the location of file directory. Once confirmed we could have the files having ExecStart locations to be copied to the respective directory.

**Comment by 555learnwithme555** [comment]
Hi @BLeeEZ , I just tested it in recent raspberry  Pi OS. It works out of the box perfect. Thanks  a lot for your effort. Happy weekend.
