### ISSUE TITLE
Does not work with Android and Mac

### ISSUE THREAD

**Issue by quaintdev** [BLeeEZ/rpi-kvm#3]
I was successfully able to connect to Linux computer using this application but both Mac and Android refuses to connect to the rpi-kvm keyboard. Any suggestions?

**Comment by BLeeEZ** [comment]
rpi-kvm is using `bluetoothctl` in the background. You can try to establish the connection manually via `bluetoothctl` as described here: https://www.makeuseof.com/manage-bluetooth-linux-with-bluetoothctl/
When the connection is established the clients are visible in the rpi-kvm web interface.

**Comment by willberriss** [comment]
Hi. I was thinking of extending kvm-service.py to work with a touchscreen input device instead of a mouse, i.e. send absolute (x,y) coordinates. Would you happen to know where I can find the USB HID usage report for a TouchScreen? I see you have Keyboard=>1 and Mouse=>2, but I cannot find out what TouchScreen would, be nor its bit mask details.  I aim to use only simple absolute (x,y) positions to control the pointer on the screen. Do you know where I can find this information? Thanks in advance.

**Comment by willberriss** [comment]
> I was successfully able to connect to Linux computer using this application but both Mac and Android refuses to connect to the rpi-kvm keyboard. Any suggestions?

For what it's worth, it works for me on a Galaxy Tab A running Android 10.  I don't recall doing anything more than just pairing it with Bluetooth.

**Comment by BLeeEZ** [comment]
> Hi. I was thinking of extending kvm_service.py to work with a touchscreen input device instead of a mouse, i.e. send absolute (x,y) coordinates. Would you happen to know where I can find the USB HID usage report for a TouchScreen? I see you have Keyboard=>1 and Mouse=>2, but I cannot find out what TouchScreen would, be nor its bit mask details. I aim to use only simple absolute (x,y) positions to control the pointer on the screen. Do you know where I can find this information? Thanks in advance.

This sounds great. I documented the process of extending the "standard" mouse/keyboard HID descriptor  to support a second horizontal mouse wheel (Logitech MX master 3) here: [hid-descriptors](https://github.com/BLeeEZ/rpi-kvm/tree/main/docu/hid-descriptors.md)
The USB documentation regarding the USB usage tables can be found here together with some other useful links: [reading](https://github.com/BLeeEZ/rpi-kvm/tree/main/docu/reading.md)

**Comment by BLeeEZ** [comment]
> I was successfully able to connect to Linux computer using this application but both Mac and Android refuses to connect to the rpi-kvm keyboard. Any suggestions?

I am using rpi-kvm without additional tools on my iPhone, iPad, Mac, Linux machine and Windows PC. I don't have a Android device so I can't tell you, but it should work as expected.

**Comment by BLeeEZ** [comment]
@willberriss for further discussions regarding touch screen integration, I would suggest that you open a new "issue".

I close this bug ticket now.

**Comment by willberriss** [comment]
> > Hi. I was thinking of extending kvm_service.py to work with a touchscreen input device instead of a mouse, i.e. send absolute (x,y) coordinates. Would you happen to know where I can find the USB HID usage report for a TouchScreen? I see you have Keyboard=>1 and Mouse=>2, but I cannot find out what TouchScreen would, be nor its bit mask details. I aim to use only simple absolute (x,y) positions to control the pointer on the screen. Do you know where I can find this information? Thanks in advance.
> 
> This sounds great. I documented the process of extending the "standard" mouse/keyboard HID descriptor to support a second horizontal mouse wheel (Logitech MX master 3) here: [hid-descriptors](https://github.com/BLeeEZ/rpi-kvm/tree/main/docu/hid-descriptors.md) The USB documentation regarding the USB usage tables can be found here together with some other useful links: [reading](https://github.com/BLeeEZ/rpi-kvm/tree/main/docu/reading.md)

Thank you very much indeed. I’ll have a good read. BLeeEZ is a great software application by the way.
